### ISSUE TITLE
Empty Result after GeneralUtility::getURL 

### ISSUE THREAD

**Issue by fischhase** [smichaelsen/typo3-pagepath#6]
TYPO3 7.6.15
PHP 5.6
pagepath Version 1.1.6

Hallo Sebastian,

I just found your EXT and I wanted to generate a frontend-link (later by a backenduser). For my tests I just tried to build a viewhelper that shows the link in a frontend template.

The "Test"-String is well returned by the viewhelper, even if I return it out of your pagepath extension. I just checked if the all classes were found. But the $result of pagepath returns empty. When I go through your script, I get following values:

print_r($data) in Line 35
Array
(
    [id] =>135
)

echo ($url) in Line 38
-> http://www.wob4u.de/index.php?eID=pagepath&data=eyJpZCI6MTM1fQ==

echo  $result; in Line  47
-> nothing/empty

So GeneralUtility::getURL does not return a result. This might be a bug?

Here the viewhelper:
[MailpathViewHelper.txt](https://github.com/smichaelsen/typo3-pagepath/files/906034/MailpathViewHelper.txt)

Bye and many thanks
Martin

**Comment by fischhase** [comment]
push :-)

**Comment by kvonspiczak** [comment]
Hey, are you still facing this issue?
I had a similar case and debugged it because it worked like a charm locally but not on the dev server.
On our dev server we're using htpasswd and thus need to authenticate before accessing the frontend.
That was the reason why getURL failed. I debugged it and passed an additional array to getURL, which then was populated and filled with more error details. See last parameter in `GeneralUtility::getURL`.

Hope it helps
cheers

**Comment by smichaelsen** [comment]
Should work now with Version 2.0
