### ISSUE TITLE
empty url for HTTPS links on TYPO3 8.7.11

### ISSUE THREAD

**Issue by kvonspiczak** [smichaelsen/typo3-pagepath#8]
Hi,

on TYPO3 8.7.11, pagepath (version 1.1.6) does not generate working HTTPS URL's.
We have a multi domain setup, where all links should be generated with https url scheme.
I saw that the `class.tx_pagepath_api.php` checks the field `url_scheme` on a page record in `getSiteUrl`. This field got removed [see here](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.6/Breaking-79302-MovedPagesurlSchemeToCompatibility7Extension.html)

**Comment by lsascha** [comment]
I had the same issue, but changing the mentioned part did not fix it.
Unfortunately since i could only reproduce it on the test-server where https and .htaccess access-rights are setup i started to quickly hack something together on my own which uses extbase and pageTypes instead of eID stuff.

I know its slower, but that did not really matter for my case.
I dont want to advertise it, but maybe you want to have a try.
https://github.com/lsascha/typo3-wm_pagepath

You can call it just like dmitry's pagepath extension with the Utility class
`Webmatch\WmPagepath\Utility\PagePathUtility::getPagePath($targetPageUid, $parametersAsArray, $optionalPageType)`

Haven't tested it much yet though. For example if it works with multi-domain setups etc. But it works on for me on the https test-server.

**Comment by smichaelsen** [comment]
Version 2.0 does not rely anymore on the `url_scheme` field and the scheme detection should work properly.
